### ISSUE TITLE
Doesnt seem to be responsive as a twitter card

### ISSUE THREAD

**Issue by molebox** [microlinkhq/cards#162]
### Prerequisites

- [ x ] I'm using the last version.
- [ x ] My node version is the same as declared as `package.json`.

### Subject of the issue

I love this, but it doesnt seem to be responsive or follow the sizing for a twitter card: 

![boo](https://user-images.githubusercontent.com/22930449/109707471-8024af80-7b9a-11eb-8543-44419729a9a8.PNG)

![boo2](https://user-images.githubusercontent.com/22930449/109707810-e7dafa80-7b9a-11eb-94b9-870aa743f8db.PNG)

![boo3](https://user-images.githubusercontent.com/22930449/109708086-3b4d4880-7b9b-11eb-8ffd-04d90cf2f57f.PNG)

### Steps to reproduce

check the image above.

Also, this is how im using it:

```
  const headline =
    "This is my blog where I write about stuff im working on and things i find interesting";
  const caption = "My articles, tutorials and thoughts. Under one roof";
  const domain = "richardhaines.dev";
  const backgroundImage = "/diamonds.png";

  const api = "https://i.microlink.io/";
  const cardUrl = `https://cards.microlink.io/?preset=richhaines&headline=${headline}&caption=${caption}&domain=${domain}&backgroundImage=${backgroundImage}`;
  const image = `${api}${encodeURIComponent(cardUrl)}`;
```

### Expected behaviour

Id expect it to be responsive and fit the twitter cards

### Actual behaviour

It seems to be zoomed in

**Comment by Kikobeats** [comment]
It depends on the template constraints and that template was created by you 😛

The image dimensions are constant over time. You can verify how the screenshot will be taken, you can see it removing `/editor` from the URL:

https://cards.microlink.io/?preset=richhaines

If your use case is to use them as Twitter Card images, then you need to take into account the Twitter Card image dimension restrictions in order to well-design the card that fits on the Twitter preview.

For an example, see how [pedro](https://cards.microlink.io/editor?preset=pedro) preview fits perfect

<img width="1418" alt="Screen Shot 2021-03-02 at 22 40 12" src="https://user-images.githubusercontent.com/2096101/109718958-42c71e80-7ba8-11eb-8a9e-32457f45a53d.png">

**Comment by molebox** [comment]
> It depends on the template constraints and that template was created by you 😛
> 
> The image dimensions are constant over time. You can verify how the screenshot will be taken, you can see it removing `/editor` from the URL:
> 
> https://cards.microlink.io/?preset=richhaines
> 
> If your use case is to use them as Twitter Card images, then you need to take into account the Twitter Card image dimension restrictions in order to well-design the card that fits on the Twitter preview.
> 
> For an example, see how [pedro](https://cards.microlink.io/editor?preset=pedro) preview fits perfect
> 
> <img alt="Screen Shot 2021-03-02 at 22 40 12" width="1418" src="https://user-images.githubusercontent.com/2096101/109718958-42c71e80-7ba8-11eb-8a9e-32457f45a53d.png">

Thanks for the quick response! Right ok, so i have to set the height and width of the card so that it matches what the twitter crad will be?

**Comment by molebox** [comment]
Im closing this as it appears that its an issue with my code as opposed to the service
